export const EMPLOYE_LIST_REQUEST = 'EMPLOYE_LIST_REQUEST';
export const EMPLOYE_LIST_SUCCESS = 'EMPLOYE_LIST_SUCCESS';
export const EMPLOYE_LIST_FAIL = 'EMPLOYE_LIST_FAIL';

export const EMPLOYE_DETAILS_REQUEST = 'EMPLOYE_DETAILS_REQUEST';
export const EMPLOYE_DETAILS_SUCCESS = 'EMPLOYE_DETAILS_SUCCESS';
export const EMPLOYE_DETAILS_FAIL = 'EMPLOYE_DETAILS_FAIL';
